--------------------------------------------------------
--  Fichier créé - mercredi-avril-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VIGNETTE
--------------------------------------------------------

  CREATE TABLE "AMINE"."VIGNETTE" 
   (	"CODE" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"DATE_DEB" DATE, 
	"DATE_EXP" DATE, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AMINE.VIGNETTE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index VIGNETTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."VIGNETTE_PK" ON "AMINE"."VIGNETTE" ("CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VIGNETTE
--------------------------------------------------------

  ALTER TABLE "AMINE"."VIGNETTE" ADD CONSTRAINT "VIGNETTE_PK" PRIMARY KEY ("CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."VIGNETTE" MODIFY ("CODE" NOT NULL ENABLE);
