--------------------------------------------------------
--  Fichier créé - mercredi-avril-01-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VISITE
--------------------------------------------------------

  CREATE TABLE "AMINE"."VISITE" 
   (	"ID" NUMBER, 
	"MATRICULE" VARCHAR2(20 BYTE), 
	"COMPAGNIE" VARCHAR2(20 BYTE), 
	"CODE" NUMBER, 
	"DATE_DEB" DATE, 
	"DATE_EXP" DATE, 
	"PRIX" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into AMINE.VISITE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index VISITE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "AMINE"."VISITE_PK" ON "AMINE"."VISITE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table VISITE
--------------------------------------------------------

  ALTER TABLE "AMINE"."VISITE" ADD CONSTRAINT "VISITE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AMINE"."VISITE" MODIFY ("ID" NOT NULL ENABLE);
